package sitori;

import javax.swing.ImageIcon;
import sitori.storage.StorageView;
import sitori.item_category.ItemCategoryView;
import sitori.item.ItemView;
import sitori.item_in.ItemInView;
import sitori.item_out.ItemOutView;
import sitori.last_activity.LastActivityView;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author lucky
 */
public class Main extends javax.swing.JFrame {
    StorageView storageView;
    ItemCategoryView itemCategoryView;
    ItemView itemView;
    ItemInView itemInView;
    ItemOutView itemOutView;
    LastActivityView lastActivityView;


    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/sitori/resource/sitori-128.png"));
        this.setIconImage(icon.getImage());
                
        storageView = new StorageView();
        itemCategoryView = new ItemCategoryView();
        itemView = new ItemView();
        itemInView = new ItemInView();
        itemOutView = new ItemOutView();
        lastActivityView = new LastActivityView();
        
        ContentPanel.add(storageView);
        ContentPanel.add(itemCategoryView);
        ContentPanel.add(itemView);
        ContentPanel.add(itemInView);
        ContentPanel.add(itemOutView);
        ContentPanel.add(lastActivityView);
        
        storageView.setVisible(false);
        itemCategoryView.setVisible(false);
        itemView.setVisible(false);
        itemInView.setVisible(false);
        itemOutView.setVisible(false);
        lastActivityView.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        StorageMenuBtn = new javax.swing.JPanel();
        StorageLabel = new javax.swing.JLabel();
        ItemCategoryMenuBtn = new javax.swing.JPanel();
        ItemCategoryLabel = new javax.swing.JLabel();
        ItemMenuBtn = new javax.swing.JPanel();
        ItemLabel = new javax.swing.JLabel();
        ItemInMenuBtn = new javax.swing.JPanel();
        ItemInLabel = new javax.swing.JLabel();
        ItemOutMenuBtn = new javax.swing.JPanel();
        ItemOutLabel = new javax.swing.JLabel();
        LastActivityMenuBtn = new javax.swing.JPanel();
        LastActivityLabel = new javax.swing.JLabel();
        LogoContainer = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jPanel8.setBackground(new java.awt.Color(42, 110, 224));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(240, 240, 240)));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitori/resource/home.png"))); // NOI18N
        jLabel6.setText("Storage");
        jLabel6.setToolTipText("");
        jLabel6.setAlignmentX(0.5F);
        jLabel6.setIconTextGap(15);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sitori");
        setBackground(new java.awt.Color(240, 240, 240));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(950, 650));

        MainPanel.setBackground(new java.awt.Color(240, 240, 240));
        MainPanel.setPreferredSize(new java.awt.Dimension(850, 0));

        SidePanel.setBackground(new java.awt.Color(42, 110, 224));
        SidePanel.setMinimumSize(new java.awt.Dimension(200, 364));
        SidePanel.setPreferredSize(new java.awt.Dimension(200, 364));
        SidePanel.setRequestFocusEnabled(false);

        StorageMenuBtn.setBackground(new java.awt.Color(42, 110, 224));
        StorageMenuBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(240, 240, 240)));
        StorageMenuBtn.setMinimumSize(new java.awt.Dimension(150, 50));
        StorageMenuBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        StorageMenuBtn.setRequestFocusEnabled(false);

        StorageLabel.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        StorageLabel.setForeground(new java.awt.Color(240, 240, 240));
        StorageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StorageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitori/resource/home.png"))); // NOI18N
        StorageLabel.setText("Storage");
        StorageLabel.setToolTipText("");
        StorageLabel.setAlignmentX(0.5F);
        StorageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StorageLabel.setIconTextGap(15);
        StorageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StorageLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout StorageMenuBtnLayout = new javax.swing.GroupLayout(StorageMenuBtn);
        StorageMenuBtn.setLayout(StorageMenuBtnLayout);
        StorageMenuBtnLayout.setHorizontalGroup(
            StorageMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StorageMenuBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StorageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        StorageMenuBtnLayout.setVerticalGroup(
            StorageMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StorageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ItemCategoryMenuBtn.setBackground(new java.awt.Color(42, 110, 224));
        ItemCategoryMenuBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(240, 240, 240)));
        ItemCategoryMenuBtn.setMinimumSize(new java.awt.Dimension(150, 50));
        ItemCategoryMenuBtn.setPreferredSize(new java.awt.Dimension(150, 50));

        ItemCategoryLabel.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        ItemCategoryLabel.setForeground(new java.awt.Color(240, 240, 240));
        ItemCategoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ItemCategoryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitori/resource/folder.png"))); // NOI18N
        ItemCategoryLabel.setText("Item Category");
        ItemCategoryLabel.setToolTipText("");
        ItemCategoryLabel.setAlignmentX(0.5F);
        ItemCategoryLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemCategoryLabel.setIconTextGap(15);
        ItemCategoryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemCategoryLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ItemCategoryMenuBtnLayout = new javax.swing.GroupLayout(ItemCategoryMenuBtn);
        ItemCategoryMenuBtn.setLayout(ItemCategoryMenuBtnLayout);
        ItemCategoryMenuBtnLayout.setHorizontalGroup(
            ItemCategoryMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemCategoryMenuBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ItemCategoryMenuBtnLayout.setVerticalGroup(
            ItemCategoryMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ItemMenuBtn.setBackground(new java.awt.Color(42, 110, 224));
        ItemMenuBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(240, 240, 240)));
        ItemMenuBtn.setMinimumSize(new java.awt.Dimension(150, 50));
        ItemMenuBtn.setPreferredSize(new java.awt.Dimension(150, 50));

        ItemLabel.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        ItemLabel.setForeground(new java.awt.Color(240, 240, 240));
        ItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ItemLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitori/resource/file.png"))); // NOI18N
        ItemLabel.setText("Item");
        ItemLabel.setToolTipText("");
        ItemLabel.setAlignmentX(0.5F);
        ItemLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemLabel.setIconTextGap(15);
        ItemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ItemMenuBtnLayout = new javax.swing.GroupLayout(ItemMenuBtn);
        ItemMenuBtn.setLayout(ItemMenuBtnLayout);
        ItemMenuBtnLayout.setHorizontalGroup(
            ItemMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemMenuBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ItemMenuBtnLayout.setVerticalGroup(
            ItemMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ItemInMenuBtn.setBackground(new java.awt.Color(42, 110, 224));
        ItemInMenuBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(240, 240, 240)));
        ItemInMenuBtn.setMinimumSize(new java.awt.Dimension(150, 50));
        ItemInMenuBtn.setPreferredSize(new java.awt.Dimension(150, 50));

        ItemInLabel.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        ItemInLabel.setForeground(new java.awt.Color(240, 240, 240));
        ItemInLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ItemInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitori/resource/file-plus.png"))); // NOI18N
        ItemInLabel.setText("Item In");
        ItemInLabel.setToolTipText("");
        ItemInLabel.setAlignmentX(0.5F);
        ItemInLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemInLabel.setIconTextGap(15);
        ItemInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemInLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ItemInMenuBtnLayout = new javax.swing.GroupLayout(ItemInMenuBtn);
        ItemInMenuBtn.setLayout(ItemInMenuBtnLayout);
        ItemInMenuBtnLayout.setHorizontalGroup(
            ItemInMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemInMenuBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ItemInMenuBtnLayout.setVerticalGroup(
            ItemInMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ItemOutMenuBtn.setBackground(new java.awt.Color(42, 110, 224));
        ItemOutMenuBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(240, 240, 240)));
        ItemOutMenuBtn.setMinimumSize(new java.awt.Dimension(150, 50));
        ItemOutMenuBtn.setPreferredSize(new java.awt.Dimension(150, 50));

        ItemOutLabel.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        ItemOutLabel.setForeground(new java.awt.Color(240, 240, 240));
        ItemOutLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ItemOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitori/resource/file-minus.png"))); // NOI18N
        ItemOutLabel.setText("Item Out");
        ItemOutLabel.setToolTipText("");
        ItemOutLabel.setAlignmentX(0.5F);
        ItemOutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemOutLabel.setIconTextGap(15);
        ItemOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemOutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ItemOutMenuBtnLayout = new javax.swing.GroupLayout(ItemOutMenuBtn);
        ItemOutMenuBtn.setLayout(ItemOutMenuBtnLayout);
        ItemOutMenuBtnLayout.setHorizontalGroup(
            ItemOutMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemOutMenuBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ItemOutMenuBtnLayout.setVerticalGroup(
            ItemOutMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        LastActivityMenuBtn.setBackground(new java.awt.Color(42, 110, 224));
        LastActivityMenuBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(240, 240, 240)));
        LastActivityMenuBtn.setMinimumSize(new java.awt.Dimension(150, 50));
        LastActivityMenuBtn.setPreferredSize(new java.awt.Dimension(150, 50));

        LastActivityLabel.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        LastActivityLabel.setForeground(new java.awt.Color(240, 240, 240));
        LastActivityLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitori/resource/clock.png"))); // NOI18N
        LastActivityLabel.setText("Last Activity");
        LastActivityLabel.setToolTipText("");
        LastActivityLabel.setAlignmentX(0.5F);
        LastActivityLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LastActivityLabel.setIconTextGap(15);
        LastActivityLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LastActivityLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LastActivityMenuBtnLayout = new javax.swing.GroupLayout(LastActivityMenuBtn);
        LastActivityMenuBtn.setLayout(LastActivityMenuBtnLayout);
        LastActivityMenuBtnLayout.setHorizontalGroup(
            LastActivityMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LastActivityMenuBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LastActivityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LastActivityMenuBtnLayout.setVerticalGroup(
            LastActivityMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LastActivityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        LogoContainer.setBackground(new java.awt.Color(42, 110, 224));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitori/resource/logo.png"))); // NOI18N

        javax.swing.GroupLayout LogoContainerLayout = new javax.swing.GroupLayout(LogoContainer);
        LogoContainer.setLayout(LogoContainerLayout);
        LogoContainerLayout.setHorizontalGroup(
            LogoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoContainerLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LogoContainerLayout.setVerticalGroup(
            LogoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoContainerLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemCategoryMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(ItemMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(ItemOutMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(LastActivityMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(StorageMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(ItemInMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(LogoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addComponent(LogoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(StorageMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemCategoryMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ItemMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemInMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemOutMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(LastActivityMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        ContentPanel.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
            .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1128, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StorageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StorageLabelMouseClicked
        StorageLabel.setFont(new Font("Noto Sans", Font.BOLD, 17));
        StorageLabel.setForeground(new Color(0,30,143));
        StorageLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/home-active.png")));
        StorageMenuBtn.setBackground(new Color(115,156,255));
        
        ItemCategoryLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemCategoryLabel.setForeground(new Color(240,240,240));
        ItemCategoryLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/folder.png")));
        ItemCategoryMenuBtn.setBackground(new Color(42,110,244));
        
        ItemLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemLabel.setForeground(new Color(240,240,240));
        ItemLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file.png")));
        ItemMenuBtn.setBackground(new Color(42,110,244));
        
        ItemInLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemInLabel.setForeground(new Color(240,240,240));
        ItemInLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-plus.png")));
        ItemInMenuBtn.setBackground(new Color(42,110,244));
        
        ItemOutLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemOutLabel.setForeground(new Color(240,240,240));
        ItemOutLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-minus.png")));
        ItemOutMenuBtn.setBackground(new Color(42,110,244));
        
        LastActivityLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        LastActivityLabel.setForeground(new Color(240,240,240));
        LastActivityLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/clock.png")));
        LastActivityMenuBtn.setBackground(new Color(42,110,244));
        
        storageView.setVisible(true);
        itemCategoryView.setVisible(false);
        itemView.setVisible(false);
        itemInView.setVisible(false);
        itemOutView.setVisible(false);
        lastActivityView.setVisible(false);
    }//GEN-LAST:event_StorageLabelMouseClicked

    private void ItemCategoryLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemCategoryLabelMouseClicked
        StorageLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        StorageLabel.setForeground(new Color(240,240,240));
        StorageLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/home.png")));
        StorageMenuBtn.setBackground(new Color(42,110,244));
        
        ItemCategoryLabel.setFont(new Font("Noto Sans", Font.BOLD, 17));
        ItemCategoryLabel.setForeground(new Color(0,30,143));
        ItemCategoryLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/folder-active.png")));
        ItemCategoryMenuBtn.setBackground(new Color(115,156,255));
        
        ItemLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemLabel.setForeground(new Color(240,240,240));
        ItemLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file.png")));
        ItemInMenuBtn.setBackground(new Color(42,110,244));
        
        ItemInLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemInLabel.setForeground(new Color(240,240,240));
        ItemInLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-plus.png")));
        ItemMenuBtn.setBackground(new Color(42,110,244));
        
        ItemOutLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemOutLabel.setForeground(new Color(240,240,240));
        ItemOutLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-minus.png")));
        ItemOutMenuBtn.setBackground(new Color(42,110,244));
        
        LastActivityLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        LastActivityLabel.setForeground(new Color(240,240,240));
        LastActivityLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/clock.png")));
        LastActivityMenuBtn.setBackground(new Color(42,110,244));
        
        storageView.setVisible(false);
        itemCategoryView.setVisible(true);
        itemView.setVisible(false);
        itemInView.setVisible(false);
        itemOutView.setVisible(false);
        lastActivityView.setVisible(false);
    }//GEN-LAST:event_ItemCategoryLabelMouseClicked

    private void ItemLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemLabelMouseClicked
        StorageLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        StorageLabel.setForeground(new Color(240,240,240));
        StorageLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/home.png")));
        StorageMenuBtn.setBackground(new Color(42,110,244));
        
        ItemCategoryLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemCategoryLabel.setForeground(new Color(240,240,240));
        ItemCategoryLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/folder.png")));
        ItemCategoryMenuBtn.setBackground(new Color(42,110,244));
        
        ItemLabel.setFont(new Font("Noto Sans", Font.BOLD, 17));
        ItemLabel.setForeground(new Color(0,30,143));
        ItemLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-active.png")));
        ItemMenuBtn.setBackground(new Color(115,156,255));
        
        ItemInLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemInLabel.setForeground(new Color(240,240,240));
        ItemInLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-plus.png")));
        ItemInMenuBtn.setBackground(new Color(42,110,244));
        
        ItemOutLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemOutLabel.setForeground(new Color(240,240,240));
        ItemOutLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-minus.png")));
        ItemOutMenuBtn.setBackground(new Color(42,110,244));
        
        LastActivityLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        LastActivityLabel.setForeground(new Color(240,240,240));
        LastActivityLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/clock.png")));
        LastActivityMenuBtn.setBackground(new Color(42,110,244));
        
        storageView.setVisible(false);
        itemCategoryView.setVisible(false);
        itemView.setVisible(true);
        itemInView.setVisible(false);
        itemOutView.setVisible(false);
        lastActivityView.setVisible(false);
    }//GEN-LAST:event_ItemLabelMouseClicked

    private void ItemInLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemInLabelMouseClicked
        StorageLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        StorageLabel.setForeground(new Color(240,240,240));
        StorageLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/home.png")));
        StorageMenuBtn.setBackground(new Color(42,110,244));
        
        ItemCategoryLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemCategoryLabel.setForeground(new Color(240,240,240));
        ItemCategoryLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/folder.png")));
        ItemCategoryMenuBtn.setBackground(new Color(42,110,244));
        
        ItemLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemLabel.setForeground(new Color(240,240,240));
        ItemLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file.png")));
        ItemMenuBtn.setBackground(new Color(42,110,244));
        
        ItemInLabel.setFont(new Font("Noto Sans", Font.BOLD, 17));
        ItemInLabel.setForeground(new Color(0,30,143));
        ItemInLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-plus-active.png")));
        ItemInMenuBtn.setBackground(new Color(115,156,255));
        
        ItemOutLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemOutLabel.setForeground(new Color(240,240,240));
        ItemOutLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-minus.png")));
        ItemOutMenuBtn.setBackground(new Color(42,110,244));
        
        LastActivityLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        LastActivityLabel.setForeground(new Color(240,240,240));
        LastActivityLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/clock.png")));
        LastActivityMenuBtn.setBackground(new Color(42,110,244));
        
        storageView.setVisible(false);
        itemCategoryView.setVisible(false);
        itemView.setVisible(false);
        itemInView.setVisible(true);
        itemOutView.setVisible(false);
        lastActivityView.setVisible(false);
    }//GEN-LAST:event_ItemInLabelMouseClicked

    private void ItemOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemOutLabelMouseClicked
        StorageLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        StorageLabel.setForeground(new Color(240,240,240));
        StorageLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/home.png")));
        StorageMenuBtn.setBackground(new Color(42,110,244));
        
        ItemCategoryLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemCategoryLabel.setForeground(new Color(240,240,240));
        ItemCategoryLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/folder.png")));
        ItemCategoryMenuBtn.setBackground(new Color(42,110,244));
        
        ItemLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemLabel.setForeground(new Color(240,240,240));
        ItemLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file.png")));
        ItemMenuBtn.setBackground(new Color(42,110,244));
        
        ItemInLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemInLabel.setForeground(new Color(240,240,240));
        ItemInLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-plus.png")));
        ItemInMenuBtn.setBackground(new Color(42,110,244));
        
        ItemOutLabel.setFont(new Font("Noto Sans", Font.BOLD, 17));
        ItemOutLabel.setForeground(new Color(0,30,143));
        ItemOutLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-minus-active.png")));
        ItemOutMenuBtn.setBackground(new Color(115,156,255));
        
        LastActivityLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        LastActivityLabel.setForeground(new Color(240,240,240));
        LastActivityLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/clock.png")));
        LastActivityMenuBtn.setBackground(new Color(42,110,244));
        
        storageView.setVisible(false);
        itemCategoryView.setVisible(false);
        itemView.setVisible(false);
        itemInView.setVisible(false);
        itemOutView.setVisible(true);
        lastActivityView.setVisible(false);
    }//GEN-LAST:event_ItemOutLabelMouseClicked

    private void LastActivityLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastActivityLabelMouseClicked
        StorageLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        StorageLabel.setForeground(new Color(240,240,240));
        StorageLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/home.png")));
        StorageMenuBtn.setBackground(new Color(42,110,244));
        
        ItemCategoryLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemCategoryLabel.setForeground(new Color(240,240,240));
        ItemCategoryLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/folder.png")));
        ItemCategoryMenuBtn.setBackground(new Color(42,110,244));
        
        ItemLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemLabel.setForeground(new Color(240,240,240));
        ItemLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file.png")));
        ItemMenuBtn.setBackground(new Color(42,110,244));
        
        ItemInLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemInLabel.setForeground(new Color(240,240,240));
        ItemInLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-plus.png")));
        ItemInMenuBtn.setBackground(new Color(42,110,244));
        
        ItemOutLabel.setFont(new Font("Noto Sans", Font.PLAIN, 17));
        ItemOutLabel.setForeground(new Color(240,240,240));
        ItemOutLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/file-minus.png")));
        ItemOutMenuBtn.setBackground(new Color(42,110,244));
        
        LastActivityLabel.setFont(new Font("Noto Sans", Font.BOLD, 17));
        LastActivityLabel.setForeground(new Color(0,30,143));
        LastActivityLabel.setIcon(new ImageIcon(getClass().getResource("/sitori/resource/clock-active.png")));
        LastActivityMenuBtn.setBackground(new Color(115,156,255));
        
        storageView.setVisible(false);
        itemCategoryView.setVisible(false);
        itemView.setVisible(false);
        itemInView.setVisible(false);
        itemOutView.setVisible(false);
        lastActivityView.setVisible(true);
    }//GEN-LAST:event_LastActivityLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JLabel ItemCategoryLabel;
    private javax.swing.JPanel ItemCategoryMenuBtn;
    private javax.swing.JLabel ItemInLabel;
    private javax.swing.JPanel ItemInMenuBtn;
    private javax.swing.JLabel ItemLabel;
    private javax.swing.JPanel ItemMenuBtn;
    private javax.swing.JLabel ItemOutLabel;
    private javax.swing.JPanel ItemOutMenuBtn;
    private javax.swing.JLabel LastActivityLabel;
    private javax.swing.JPanel LastActivityMenuBtn;
    private javax.swing.JPanel LogoContainer;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel StorageLabel;
    private javax.swing.JPanel StorageMenuBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
